[package]
name = "pglx"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.18"
clap = { version = "4.4.11", features = ["derive"] }
color-eyre = "0.6.2"
serde = { version = "1.0.164", features = ["derive"] }
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }
tokio-postgres = "0.7.8"
ureq = { version = "2.7.1", features = ["json"], default-features = false }
